// Code generated by "stringer -type=Effect"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Arpeggio-0]
	_ = x[SlideUp-1]
	_ = x[SlideDown-2]
	_ = x[Portamento-3]
	_ = x[Vibrato-4]
	_ = x[PortamentoVolSlide-5]
	_ = x[VibratoVolSlide-6]
	_ = x[Tremolo-7]
	_ = x[NotUsed8-8]
	_ = x[SetSampleOffset-9]
	_ = x[VolSlide-10]
	_ = x[PositionJump-11]
	_ = x[SetVol-12]
	_ = x[PatternBreak-13]
	_ = x[Extended-14]
	_ = x[SetSpeed-15]
	_ = x[SetFilter-16]
	_ = x[FineSlideUp-17]
	_ = x[FineSlideDown-18]
	_ = x[GlissandoControl-19]
	_ = x[SetVibratoWaveform-20]
	_ = x[SetLoop-21]
	_ = x[JumpToLoop-22]
	_ = x[SetTremoloWaveform-23]
	_ = x[NotUsedE8-24]
	_ = x[RetrigNote-25]
	_ = x[FineVolSlideUp-26]
	_ = x[FineVolSlideDown-27]
	_ = x[NoteCut-28]
	_ = x[NoteDelay-29]
	_ = x[PatternDelay-30]
	_ = x[InvertLoop-31]
}

const _Effect_name = "ArpeggioSlideUpSlideDownPortamentoVibratoPortamentoVolSlideVibratoVolSlideTremoloNotUsed8SetSampleOffsetVolSlidePositionJumpSetVolPatternBreakExtendedSetSpeedSetFilterFineSlideUpFineSlideDownGlissandoControlSetVibratoWaveformSetLoopJumpToLoopSetTremoloWaveformNotUsedE8RetrigNoteFineVolSlideUpFineVolSlideDownNoteCutNoteDelayPatternDelayInvertLoop"

var _Effect_index = [...]uint16{0, 8, 15, 24, 34, 41, 59, 74, 81, 89, 104, 112, 124, 130, 142, 150, 158, 167, 178, 191, 207, 225, 232, 242, 260, 269, 279, 293, 309, 316, 325, 337, 347}

func (i Effect) String() string {
	if i < 0 || i >= Effect(len(_Effect_index)-1) {
		return "Effect(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Effect_name[_Effect_index[i]:_Effect_index[i+1]]
}
